Added Method PUT
ronanrodrigo/Frisbee pull request #27
Opened 2018-02-12 05:11 UTC by amadeu01

Implement other HTTP verbs #8 
Added PUT verb

2018-03-12 13:03 UTC, ronanrodrigo requested changes
Nice! I just made a request-change about access control and unit tests at `NetworkPut`.

Thanks for the support @amadeu01

2018-03-12 13:03 UTC, ronanrodrigo commented on Sources/Frisbee/Requestables/Putable.swift
> +protocol Putable {
Make this public

2018-03-12 13:04 UTC, amadeu01 commented on Sources/Frisbee/Requestables/Putable.swift
> +protocol Putable {
Okay!

2018-03-12 13:07 UTC, ronanrodrigo commented on Sources/Frisbee/Requestables/NetworkPut.swift
> +public final class NetworkPut: Putable {
Could you make unit tests for this guy?

2018-03-12 13:07 UTC, ronanrodrigo commented on Sources/Frisbee/Requestables/NetworkPut.swift
> +public final class NetworkPut: Putable {
> I forgot to write this comment 🤪

2018-03-12 15:42 UTC, amadeu01 commented on Sources/Frisbee/Requestables/NetworkPut.swift
> +public final class NetworkPut: Putable {
sure. I will

2018-04-19 11:37 UTC, amadeu01 commented
@ronanrodrigo I forgot to update my PR, sorry. I'll do it soon

2018-04-25 15:51 UTC, amadeu01 commented
Hi @ronanrodrigo

I will update my PR soon, sorry for my delay

2018-05-04 11:48 UTC, amadeu01 commented on Sources/Frisbee/Requestables/Putable.swift
> +protocol Putable {
Done

2018-05-04 12:02 UTC, amadeu01 commented on Sources/Frisbee/Requestables/NetworkPut.swift
> +public final class NetworkPut: Putable {
Done

2018-05-04 16:25 UTC, amadeu01 commented
@ronanrodrigo o `put` é muito parecido com o `post`



> POST:
> 
> Used to modify and update a resource
> 
```
 POST /questions/<existing_question> HTTP/1.1
 Host: www.example.com/
```
> Note that the following is an error:
> 
> POST /questions/<new_question> HTTP/1.1
> Host: www.example.com/
> If the URL is not yet created, you should not be using POST to create it while specifying the name. This should result in a 'resource not found' error because <new_question> does not exist yet. You should PUT the <new_question> resource on the server first.
> 
> You could though do something like this to create a resources using POST:
> 
```
POST /questions HTTP/1.1
Host: www.example.com/
```
> Note that in this case the resource name is not specified, the new objects URL path would be returned to you.
> 
> PUT:
> 
> Used to create a resource, or overwrite it. While you specify the resources new URL.
> 
> For a new resource:
> 
```
PUT /questions/<new_question> HTTP/1.1
Host: www.example.com/
```
> To overwrite an existing resource:

```
PUT /questions/<existing_question> HTTP/1.1
Host: www.example.com/ 
```

2018-05-04 16:32 UTC, unnamedd commented
Actually, `POST` is usually used to create new resources and `PUT` to update some existing resource. Yes, they are really similar but it is a semantic point. If you want, you can use `GET` to create new resources (or update), but you should not use.

2018-05-04 17:00 UTC, ronanrodrigo commented
May appear to be a similar code. But they do different things. And because of this they are different code. Maybe some refactor to aggregate them come up one day. But first, we must to understand if that code repetition are accidental or no. And after this we can proceed with some strategy to make the refactor. Baby steps 🚼 

By accidental duplication:

> “Duplication is generally a bad thing in software. We don’t like duplicated code. When code is truly duplicated, we are honor-bound as professionals to reduce and eliminate it.
>
> But there are different kinds of duplication. There is true duplication, in which every change to one instance necessitates the same change to every duplicate of that instance. Then there is false or accidental duplication. If two apparently duplicated sections of code evolve along different paths—if they change at different rates, and for different reasons—then they are not true duplicates. Return to them in a few years, and you’ll find that they are very different from each other.
>
> Now imagine two use cases that have very similar screen structures. The architects will likely be strongly tempted to share the code for that structure. But should they? Is that true duplication? Or it is accidental?
>
> Most likely it is accidental. As time goes by, the odds are that those two screens will diverge and eventually look very different. For this reason, care must be taken to avoid unifying them. Otherwise, separating them later will be a challenge.
>
> When you are vertically separating use cases from one another, you will run into this issue, and your temptation will be to couple the use cases because they have similar screen structures, or similar algorithms, or similar database queries and/or schemas. Be careful. Resist the temptation to commit the sin of knee-jerk elimination of duplication. Make sure the duplication is real.”
>
> Excerpt From: Robert C. Martin. “Clean Architecture: A Craftsman's Guide to Software Structure and Design (Robert C. Martin Series).” iBooks.

2018-05-04 17:32 UTC, amadeu01 commented
@ronanrodrigo  
Well, it seems that I have done everything you asked to be fixed. So, there is anything else I can do to the PR is accepted?

2018-05-04 17:33 UTC, ronanrodrigo commented
@amadeu01 I just need to finish the review. I didn't start yet :)

2018-05-04 21:17 UTC, ronanrodrigo approved these changes

2018-05-04 21:18 UTC, ronanrodrigo approved these changes
Nice job @amadeu01 thanks for your contribution. And we will keep talking about the refactor 👍

2018-05-04 21:18 UTC, merged